use crate::fixtures::*;

pub fn no_human_epistemic_check_001() -> GoldenFixture {
    let mut fixture = FixtureSchema {
        fixture_id: fixture_id("no_human_epistemic_check_001"),
        schema_version: schema_version(),
        fixture_scope: FixtureScope::Phase2AHistorical,
        need_model: need_model_schema(),
        actors: vec![actor_schema("actor_tomas", "house_tomas")],
        places: vec![place_schema("house_tomas", "Tomas house", &[])],
        doors: Vec::new(),
        containers: vec![container_schema(
            "strongbox_tomas",
            "house_tomas",
            false,
            false,
            &["coin_stack_01"],
            true,
        )],
        items: vec![item_in_container("coin_stack_01", "strongbox_tomas", true)],
        affordances: vec![
            affordance("check_container", "strongbox_tomas"),
            affordance("inspect_place", "house_tomas"),
            affordance("inspect_entity", "strongbox_tomas"),
        ],
        initial_beliefs: vec![tomas_coin_expectation_seed()],
        initial_needs: Vec::new(),
        homes: Vec::new(),
        sleep_places: Vec::new(),
        food_supplies: Vec::new(),
        known_food_sources: Vec::new(),
        workplaces: Vec::new(),
        routine_templates: Vec::new(),
        routine_assignments: Vec::new(),
        day_windows: Vec::new(),
    };
    #[expect(
        clippy::disallowed_methods,
        reason = "legacy fixture blanket food-source seeding is pinned by fixtures_load census; new fixtures must author per-actor known_food_sources edges"
    )]
    fixture.populate_known_food_sources_for_all_actors();
    fixture.canonicalize();
    GoldenFixture {
        fixture,
        contract: FixtureContract {
            fixture_id: "no_human_epistemic_check_001",
            purpose: "Provide epistemic seed data for non-human or unattended simulation checks.",
            setup: vec![
                "actor_tomas is an ordinary actor with a private expectation",
                "no controller binding or player state is required by the fixture",
                "strongbox_tomas and coin_stack_01 are physical entities",
            ],
            allowed_actions: vec![
                "check strongbox_tomas from an ordinary proposal",
                "inspect house_tomas",
                "advance without a human controller",
            ],
            expected_events_or_reports: vec![
                "ContainerChecked and ObservationRecorded can be generated by shared action machinery",
                "no human-bound epistemic privilege is required",
            ],
            acceptance_assertions: vec![
                "fixture contains no player/protagonist entity",
                "epistemic checks are ordinary actor-relative actions",
            ],
        },
    }
}
